### ISSUE TITLE
@layer级联层

### ISSUE THREAD

**Issue by Betty985** [Betty985/note#28]
[CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) [@规则](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule) 中的@layer声明了一个 级联层， 同一层内的规则将级联在一起， 这给予了开发者对层叠机制的更多控制。

# 创建方式
1.带命名的级联层
```css
@layer utilities {
  /* 创建一个名为 utilities 的级联层 */
}
/*单一命名层，不指定任何样式*/
@layer utilities
/*多个命名层，后面的级联层会覆盖前面的*/
@layer theme, layout, utilities
```
2.@import
@import(utilities.css) layer(utilities);
3. [嵌套层](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@layer#%E5%B5%8C%E5%A5%97%E5%B1%82)
```css
@layer framework {
  @layer layout {

  }
}
/*向 layout 层内部的 framework 层附加规则，用 . 连接这两层*/
@layer framework.layout {
  p {
    margin-block: 1rem;
  }
}
```
5. [匿名层](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@layer#%E5%8C%BF%E5%90%8D%E5%B1%82)
创建后无法向其添加规则
# 来源
[@layer](https://developer.mozilla.org/zh-CN/docs/Web/CSS/@layer)
