### ISSUE TITLE
position:fixed 相对父元素定位

### ISSUE THREAD

**Issue by Betty985** [Betty985/note#33]
position:fixed相对于浏览器定位。
实现相对于父元素定位：不设置top,bottom,left,right,只设置margin。
```html
<button id='btn'>移动父元素</button>
<div id='a'>
<div id='b'></div>
</div>
```
```css
#a{
    width: 200px;
    height:200px;
    border: 1px red solid;
    position: absolute
}
#b{
     width: 100px;
     height:100px;
     background: pink;
     margin: 50px;
     position: fixed
}
```
```js
 var player = document.getElementById("a");
var button = document.getElementById("btn");
function moveDown(object) {
        object.style.right = parseInt( object.style.right || 0) +11 + 'px';
 }
button.onclick = function() {
         moveDown(player);
}
```
position:fixed元素会受到父元素影响：
- 父元素设置transform会对固定定位的子元素产生影响
- 父级的z-index层次比同级元素低，会导致子元素被父级同级元素遮挡
# 参考资料
[position:fixed 相对父元素定位](https://blog.csdn.net/weixin_30364147/article/details/99902985?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1.pc_relevant_default&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1.pc_relevant_default&utm_relevant_index=2)
