### ISSUE TITLE
clamp函数

### ISSUE THREAD

**Issue by Betty985** [Betty985/note#38]
clamp() 函数的作用是把一个值限制在一个上限和下限之间，当这个值超过最小值和最大值的范围时，在最小值和最大值之间选择一个值使用。它接收三个参数：最小值、首选值、最大值。 clamp() 被用在 [<length>](https://developer.mozilla.org/zh-CN/docs/Web/CSS/length)、[<frequency>](https://developer.mozilla.org/zh-CN/docs/Web/CSS/frequency)、[<angle>](https://developer.mozilla.org/zh-CN/docs/Web/CSS/angle)、[<time>](https://developer.mozilla.org/zh-CN/docs/Web/CSS/time)、[<percentage>](https://developer.mozilla.org/zh-CN/docs/Web/CSS/percentage)、[<number>](https://developer.mozilla.org/zh-CN/docs/Web/CSS/number)、[<integer>](https://developer.mozilla.org/zh-CN/docs/Web/CSS/integer) 中都是被允许的。

clamp(MIN, VAL, MAX) 其实就是表示 [max](https://developer.mozilla.org/zh-CN/docs/Web/CSS/max)(MIN, [min](https://developer.mozilla.org/zh-CN/docs/Web/CSS/min)(VAL, MAX))

clamp() 函数接收三个用逗号分隔的表达式作为参数，按最小值、首选值、最大值的顺序排列。

当首选值比最小值要小时，则使用最小值。

当首选值介于最小值和最大值之间时，用首选值。

当首选值比最大值要大时，则使用最大值。
# demo
```html
<h1>I am fluid typography</h1>
<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. In orci orci, eleifend id risus nec, mattis rutrum velit. Suspendisse fringilla egestas erat eu convallis. Phasellus eu velit ut magna dapibus elementum cursus at ligula. Ut tempus varius nibh, nec auctor sapien iaculis sit amet. Fusce iaculis, libero quis elementum viverra, nulla ante accumsan lectus, sit amet convallis lacus ipsum vel est. Curabitur et urna non est consectetur pulvinar vel id risus. Ut vestibulum, sem in semper aliquet, felis arcu euismod sapien, ac imperdiet massa nisl quis sem. Vestibulum ac elementum felis, in tempor velit. Pellentesque purus ex, mattis at ornare quis, porta condimentum mi. Donec vestibulum ligula vel nulla blandit, quis euismod nulla vestibulum. Suspendisse potenti. Nunc neque mauris, tempor sed facilisis at, ultrices eget nulla. Pellentesque convallis ante nec augue porttitor, id tempus ante luctus.</p>

<p>Integer rutrum sollicitudin tellus, quis cursus nulla scelerisque nec. Nunc eu facilisis lorem. Maecenas faucibus sapien eleifend, semper tellus at, pharetra quam. Cras feugiat vulputate tortor at rhoncus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam non felis quis sem lobortis sodales vel id libero. Phasellus sit amet placerat lorem. </p>
```
```css
body {
  display: grid;
  place-items: center;
  margin: 0 auto;
  width: min(1000px, calc(70% + 100px));
}

h1 {
  text-align: center;
  font-family: system-ui, serif;
  font-size: clamp(1.5rem, 5vw, 3rem);
}
p {
  line-height: 1.5;
  font-size:  clamp(0.5rem, 2.5vw, 1.5rem);
}
```
# 用途
响应式和流畅的排版
# 参考资料
- [clamp()](https://developer.mozilla.org/zh-CN/docs/Web/CSS/clamp)
- [min()、max() 和 clamp()：今天要使用的三个逻辑 CSS 函数](https://web.dev/i18n/zh/min-max-clamp/)
