### ISSUE TITLE
css todo

### ISSUE THREAD

**Issue by Betty985** [Betty985/note#51]
```html
<div id='a'>abc</div>
<div id='d'>123</div>
```
```css
#a{
    background: bisque;
    width:40px;
    height:200px;
    position: fixed;
    /* position:absolute; */
    /* float: left; */
}
#d{
    background: beige;
    width:400px;
    height:200px;
}
```
